AWSTemplateFormatVersion: "2010-09-09"
Description: 'This stack will  create an S3 bucket to store the zipped lambda deployment package'

Parameters:
  BucketName:
    Description: The name of the S3 bucket which will store the Lambda deployment package
    Type: String

Resources:
  Bucket:
   Type: 'AWS::S3::Bucket'
   Properties: 
     AccessControl: BucketOwnerFullControl
     BucketName: !Ref BucketName
     Tags:
       -
         Key: Stack Name
         Value: !Ref AWS::StackName

Outputs:
  BucketName:
    Description: Bucket name - lambda.zip
    Value: !Ref BucketName
    Export:
      Name: !Sub '${AWS::StackName}-Bucket'